"""
TransitMind - Streamlit dashboard

Run from the project root:   streamlit run dashboard\\app.py
All heavy work is done by the scripts in preprocessing/, regression/, ... ;
the dashboard only reads their outputs (small CSVs and models/*.joblib).
"""
import sys
from pathlib import Path

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from preprocessing.feature_engineering import TIME_PERIODS  # noqa: E402
from reinforcement import q_learning as ql                  # noqa: E402

PROCESSED = ROOT / "data" / "processed"
MODELS = ROOT / "models"
DISCLAIMER = ("Recommendation generated by a simulation / decision-support model; "
              "not direct real-world bus control.")

st.set_page_config(page_title="TransitMind", page_icon="🚌", layout="wide")


# ------------------------------------------------------------------ data access
@st.cache_data(show_spinner=False)
def load_csv(name, **kw):
    path = PROCESSED / name
    return pd.read_csv(path, **kw) if path.exists() else None


@st.cache_data(show_spinner=False)
def total_stops():
    path = PROCESSED / "pmpml_operational_data.csv"
    if not path.exists():
        return None
    return int(pd.read_csv(path, usecols=["stop_id"])["stop_id"].nunique())


@st.cache_resource(show_spinner=False)
def load_model(name):
    path = MODELS / name
    return joblib.load(path) if path.exists() else None


@st.cache_resource(show_spinner="Preparing Q-table...")
def get_q_table():
    return ql.load_or_train()


def need(df, script):
    if df is None:
        st.warning(f"Output not found. Run `{script}` first (see README).")
        st.stop()
    return df


def ml_data():
    return need(load_csv("pmpml_ml_dataset.csv", dtype={"route_id": str, "route_short_name": str}),
                r"python preprocessing\create_ml_dataset.py")


def route_picker(df, key):
    summary = df.drop_duplicates("route_id").sort_values("total_trips", ascending=False)
    options = summary["route_short_name"].tolist()
    default = options.index("301") if "301" in options else 0
    return st.selectbox("Route", options, index=default, key=key)


def bar(ax_labels, values, title, ylabel, color="#2b6cb0", horizontal=False):
    fig, ax = plt.subplots(figsize=(7, 3.4))
    (ax.barh if horizontal else ax.bar)(ax_labels, values, color=color)
    ax.set_title(title)
    (ax.set_xlabel if horizontal else ax.set_ylabel)(ylabel)
    if not horizontal:
        plt.setp(ax.get_xticklabels(), rotation=25, ha="right")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)


# ---------------------------------------------------------------------- pages
def page_overview():
    st.title("🚌 TransitMind")
    st.caption("AI-based adaptive bus scheduling & route analysis - decision-support prototype "
               "built on PMPML GTFS schedule data")
    df = ml_data()
    summary = need(load_csv("pmpml_route_summary.csv"), r"python preprocessing\analyze_routes.py")
    rev = load_csv("pmpml_revenue_data.csv")
    c = st.columns(5)
    c[0].metric("Routes", f"{df['route_id'].nunique():,}")
    c[1].metric("Scheduled trips", f"{int(summary['total_trips'].sum()):,}")
    stops = total_stops()
    c[2].metric("Unique stops", f"{stops:,}" if stops else "n/a")
    c[3].metric("Avg trip duration", f"{summary['average_trip_duration_minutes'].mean():.0f} min")
    c[4].metric("Historical revenue records", f"{len(rev):,}" if rev is not None else "n/a")

    st.subheader("How the system works")
    st.markdown(
        "`GTFS data` → `cleaning` → `route analysis` → `feature engineering` → `regression` → "
        "`classification` → `clustering` → `ensemble comparison` → `Q-learning decision support` "
        "→ this dashboard.\n\n"
        "TransitMind studies the **scheduled** service of each PMPML route, compares several "
        "machine-learning models, groups similar routes, and finally lets a small Q-learning "
        "agent suggest a scheduling action to a human operator.")
    st.info("**Data honesty:** GTFS contains the planned timetable, not passenger counts. "
            "Targets and classes are *scheduled service activity*, not passenger demand. "
            "The revenue file is a single day in 2019 for two routes; it is a historical signal "
            "only. The Q-learning reward uses a simulated proxy environment.")


def page_route():
    st.header("Route analysis")
    df = ml_data()
    route = route_picker(df, "route_analysis")
    rows = df[df["route_short_name"] == route].set_index("time_period").reindex(TIME_PERIODS)
    first = rows.iloc[0]
    c = st.columns(5)
    c[0].metric("Scheduled trips", int(first["total_trips"]))
    c[1].metric("Unique stops", int(first["unique_stops"]))
    c[2].metric("Avg stops / trip", f"{first['average_stops']:.1f}")
    c[3].metric("Avg duration", f"{first['average_trip_duration']:.0f} min")
    c[4].metric("Route shapes", int(first["shape_count"]))
    left, right = st.columns(2)
    with left:
        bar(TIME_PERIODS, rows["scheduled_trips_in_period"].fillna(0), "Scheduled trips by time period", "trips")
    with right:
        bar(TIME_PERIODS, rows["trips_per_hour"].fillna(0), "Trips per hour by time period", "trips / hour",
            color="#dd6b20")
    st.dataframe(rows[["scheduled_trips_in_period", "trips_per_hour", "buses_required_proxy",
                       "activity_class"]].round(2))
    clusters = load_csv("route_clusters.csv", dtype={"route_id": str, "route_short_name": str})
    if clusters is not None and route in set(clusters["route_short_name"]):
        r = clusters[clusters["route_short_name"] == route].iloc[0]
        st.write(f"**Operational group:** {r['cluster']} - {r['cluster_description']}")
    rev = load_csv("pmpml_revenue_data.csv")
    if rev is not None and route.isdigit() and int(route) in set(rev["Route_No"]):
        st.subheader("Historical revenue (17 Feb 2019 only)")
        by_hour = rev[rev["Route_No"] == int(route)].groupby("Hour")["Revenue"].sum()
        bar(by_hour.index.astype(str), by_hour.values, "Revenue by hour (one historical day)", "revenue")
        st.caption("Different service date from the 2026 GTFS feed; shown as context, not as demand.")
    else:
        st.caption("No historical revenue is available for this route (revenue data covers routes 2 and 27 only).")


def page_regression():
    st.header("Regression")
    st.write("**Target:** `scheduled_trips_in_period` - number of scheduled trips of a route in a "
             "time period (scheduled service activity, **not** passenger demand).")
    res = need(load_csv("regression_results.csv"), r"python regression\train_models.py")
    st.dataframe(res[["model", "MAE", "RMSE", "R2", "CV_R2_mean"]], hide_index=True)
    c1, c2 = st.columns(2)
    with c1:
        bar(res["model"], res["R2"], "Test R² (higher is better)", "R²", horizontal=True)
    with c2:
        bar(res["model"], res["RMSE"], "Test RMSE (lower is better)", "trips", color="#c53030",
            horizontal=True)
    best = res.iloc[0]
    st.success(f"Best model on held-out routes: **{best['model']}** (R² = {best['R2']:.2f}, "
               f"MAE = {best['MAE']:.1f} trips).")
    if best["R2"] < 0.5:
        st.warning("R² is modest: route structure and time period explain only part of how many "
                   "trips are scheduled. Treat predictions as rough estimates.")
    saved = load_model("regression_models.joblib")
    df = ml_data()
    if saved:
        st.subheader("Simple prediction")
        a, b = st.columns(2)
        with a:
            route = route_picker(df, "reg_route")
        period = b.selectbox("Time period", TIME_PERIODS, key="reg_period")
        row = df[(df["route_short_name"] == route) & (df["time_period"] == period)]
        if not row.empty:
            model = saved["models"][saved["best"]]
            pred = float(model.predict(row[saved["features"]])[0])
            st.metric(f"Predicted scheduled trips ({saved['best']})", f"{pred:.1f}",
                      delta=f"actual in timetable: {int(row.iloc[0][saved['target']])}", delta_color="off")


def page_classification():
    st.header("Classification")
    st.write("**Classes:** Low / Medium / High *scheduled activity* (terciles of trips per hour). "
             "These are operational classes, not passenger-demand classes.")
    res = need(load_csv("classification_results.csv"), r"python classification\train_models.py")
    st.dataframe(res, hide_index=True)
    bar(res["model"], res["F1"], "Weighted F1 on held-out routes", "F1", horizontal=True, color="#38a169")
    cm = need(load_csv("classification_confusion.csv"), r"python classification\train_models.py")
    name = st.selectbox("Confusion matrix for model", res["model"].tolist(), key="cm_model")
    sub = cm[cm["model"] == name].pivot(index="actual", columns="predicted", values="count")
    order = [c for c in ["Low", "Medium", "High"] if c in sub.index]
    sub = sub.loc[order, order]
    fig, ax = plt.subplots(figsize=(4.2, 3.6))
    ax.imshow(sub.values, cmap="Blues")
    ax.set_xticks(range(len(order)), order)
    ax.set_yticks(range(len(order)), order)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    for i in range(len(order)):
        for j in range(len(order)):
            ax.text(j, i, int(sub.values[i, j]), ha="center", va="center")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    saved = load_model("classifier.joblib")
    if saved:
        st.subheader("Predicted operational class")
        df = ml_data()
        a, b = st.columns(2)
        with a:
            route = route_picker(df, "cls_route")
        period = b.selectbox("Time period", TIME_PERIODS, key="cls_period")
        row = df[(df["route_short_name"] == route) & (df["time_period"] == period)]
        if not row.empty:
            pred = saved["models"][saved["best"]].predict(row[saved["features"]])[0]
            st.metric(f"Predicted class ({saved['best']})", pred,
                      delta=f"timetable-derived class: {row.iloc[0]['activity_class']}", delta_color="off")


def page_clustering():
    st.header("Route clustering")
    clusters = need(load_csv("route_clusters.csv", dtype={"route_id": str, "route_short_name": str}),
                    r"python clustering\cluster_routes.py")
    prof = need(load_csv("cluster_profiles.csv"), r"python clustering\cluster_routes.py")
    metrics = load_csv("clustering_metrics.csv")
    st.subheader("What each K-Means cluster looks like")
    for _, r in prof.iterrows():
        st.markdown(f"**{r['cluster_name']}** - {int(r['routes'])} routes: {r['description']}  \n"
                    f"avg {r['mean_total_trips']:.0f} trips, {r['mean_average_stops']:.0f} stops/trip, "
                    f"{r['mean_average_trip_duration']:.0f} min per trip")
    st.caption("Descriptions are generated from cluster averages compared with the network average.")
    c1, c2 = st.columns(2)
    with c1:
        sizes = clusters["cluster"].value_counts().sort_index()
        bar(sizes.index, sizes.values, "Routes per cluster", "routes")
    with c2:
        feats = ["total_trips", "average_stops", "average_trip_duration", "unique_stops",
                 "peak_share", "route_complexity"]
        x = st.selectbox("X axis", feats, index=0, key="cx")
        y = st.selectbox("Y axis", feats, index=2, key="cy")
    fig, ax = plt.subplots(figsize=(7, 4))
    for name, g in clusters.groupby("cluster"):
        ax.scatter(g[x], g[y], s=18, alpha=0.75, label=name)
    ax.set_xlabel(x)
    ax.set_ylabel(y)
    ax.legend()
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)
    if metrics is not None:
        st.subheader("Algorithm comparison")
        st.dataframe(metrics[metrics["noise_points"].notna()][["algorithm", "k", "silhouette", "noise_points"]],
                     hide_index=True)
        elbow = metrics[metrics["algorithm"].str.startswith("K-Means")]
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.plot(elbow["k"], elbow["inertia"], marker="o")
        ax.set_title("Elbow curve (K-Means inertia)")
        ax.set_xlabel("k")
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)
    st.dataframe(clusters[["route_short_name", "cluster", "total_trips", "average_stops",
                           "average_trip_duration"]], hide_index=True)


def page_ensemble():
    st.header("Ensemble vs single models")
    st.write("Question: *does combining models improve prediction compared with a single model?*")
    res = need(load_csv("ensemble_results.csv"), r"python ensemble\compare_models.py")
    for task, metric in (("regression", "R2"), ("classification", "F1")):
        t = res[res["task"] == task].sort_values("primary_score", ascending=False)
        st.subheader(task.capitalize() + f" ({metric}, higher is better)")
        fig, ax = plt.subplots(figsize=(7, 3.8))
        colors = ["#dd6b20" if ty == "ensemble" else "#2b6cb0" for ty in t["type"]]
        ax.barh(t["model"][::-1], t["primary_score"][::-1], color=colors[::-1])
        ax.set_xlabel(metric)
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)
        bs, be = t[t["type"] == "single"].iloc[0], t[t["type"] == "ensemble"].iloc[0]
        st.write(f"Best single model: **{bs['model'].replace('[single] ', '')}** ({bs['primary_score']:.3f}) | "
                 f"best ensemble: **{be['model']}** ({be['primary_score']:.3f}) | "
                 f"**best overall: {t.iloc[0]['model'].replace('[single] ', '')}**")
    st.caption("Blue = single models, orange = ensembles. Results come from one route-grouped "
               "train/test split, so small differences are not conclusive.")


def page_qlearning():
    st.header("Adaptive scheduling - Q-learning")
    st.warning(DISCLAIMER)
    df = ml_data()
    Q = get_q_table()
    a, b, c, d = st.columns(4)
    with a:
        route = route_picker(df, "q_route")
    period = b.selectbox("Time period", TIME_PERIODS, key="q_period")
    condition = c.selectbox("Operational condition (simulated input)", ql.CONDITIONS, key="q_cond")
    row = df[(df["route_short_name"] == route) & (df["time_period"] == period)]
    if row.empty:
        st.error("No data for this route / period.")
        return
    row = row.iloc[0]
    required = float(row["buses_required_proxy"])
    available = d.number_input("Available buses", min_value=1, max_value=200,
                               value=max(1, int(round(required))), step=1, key="q_buses")
    rec = ql.recommend(Q, row["activity_class"], period, condition, int(available), required)

    st.subheader("Current state")
    s = rec["state"]
    st.write(f"Route **{route}** | {s['period']} | scheduled activity **{s['activity']}** "
             f"({row['trips_per_hour']:.1f} trips/h, schedule needs ≈ {required:.1f} buses) | "
             f"condition **{s['condition']}** | fleet level **{s['bus_level']}** | "
             f"frequency **{s['frequency_level']}**")
    st.subheader("Recommendation")
    st.success(f"**{rec['recommended_action']}**")
    st.write(f"Expected reward: **{rec['expected_return']:.2f}** (discounted return from the Q-table), "
             f"immediate reward {rec['expected_immediate_reward']:.2f}")
    st.write("**Reason:** " + rec["reason"])
    q = rec["q_values"]
    bar(list(q.keys()), list(q.values()), "Q-value of each available action", "Q-value", color="#805ad5")
    st.dataframe(pd.DataFrame({"action": list(q.keys()), "Q-value": list(q.values()),
                               "immediate reward": list(rec["immediate_rewards"].values())}),
                 hide_index=True)
    log = load_csv("qlearning_training_log.csv")
    if log is not None:
        fig, ax = plt.subplots(figsize=(7, 3))
        ax.plot(log["episode"], log["total_reward"].rolling(100, min_periods=1).mean())
        ax.set_title("Training: reward per episode (100-episode moving average)")
        ax.set_xlabel("episode")
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)
    with st.expander("What is real and what is simulated?"):
        st.markdown(
            "- **Real (GTFS schedule):** activity level, trips per hour, required-buses estimate.\n"
            "- **Simulated / proxy:** operational condition, the service-need formula, the reward, "
            "fleet/frequency levels.\n"
            "- There is **no** passenger waiting-time or occupancy data; the reward is **not** based on it.")
    st.caption(DISCLAIMER)


PAGES = {"Overview": page_overview, "Route Analysis": page_route, "Regression": page_regression,
         "Classification": page_classification, "Clustering": page_clustering,
         "Ensemble": page_ensemble, "Adaptive Scheduling (Q-Learning)": page_qlearning}

st.sidebar.title("TransitMind")
choice = st.sidebar.radio("Page", list(PAGES))
st.sidebar.caption("Decision-support prototype. Based on scheduled GTFS data; "
                   "not a real-time or passenger-demand system.")
PAGES[choice]()
